baseurl = "https://mattgrogan.info/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Matthew Grogan"
title = "Matthew Grogan"
pygmentsuseclasses = true
PygmentsCodeFences = true
pygmentsstyle = "tango"
disqusshortname = "mattgrogan" # Comment out to disable Disqus.
#pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Matthew Grogan"
gravatar = "ec22b6f91b4d5885dfcb72a4fd7c8ac9" # do not use in the same time as Avatar
# avatar = "" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
# cachebuster = false # FIXME: See issue #32.
dateform = "2006-01-02"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Don't panic"
email = "mvgnyc@gmail.com"
faviconfile = "img/leaf.ico"
gatracker = "UA-62086825-1"
github = "https://github.com/mattgrogan"
#highlightjs = true
#highlightjslanguages = ["r"] # additional languages not included in the "common" set
initials = "mg" # Displayed on single post page; DEPRECATED in v0.3.0.
#lang = "en"
linkedin = "https://www.linkedin.com/in/matthew-grogan-63610959"
twitter = "https://twitter.com/matthewvgrogan"

extracssfiles = [ "/css/tango.css" ] # In your `static/css`, add/remove files as necessary.

[taxonomies]
tag = "tags"
category = "categories"
#project = "projects"
